on: [push]

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    name: A demo job to delete workflow runs
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Delete workflow runs
        uses: ./ # Uses an action in the root directory
        id: delete-old-workflow-runs
        with:
          repository: MajorScruffy/delete-old-workflow-runs
          workflow: ".github/workflows/main.yml"
          # older-than-seconds: 3600
          # created-before: "2021-12-08T16:34:00Z"
          # actor: test@test.com
          # branch: main
          # event: push
          # event: completed
          # what-if: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
