on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          repository: MajorScruffy/delete-old-workflow-runs
          workflow: ".github/workflows/main2.yml"
          # created-before: "2021-12-09T16:34:00Z"
          # actor: test@test.com
          # branch: main
          # event: push
          # event: completed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"